export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmModel: process.env.LLM_MODEL ?? "gemini-2.5-flash",
  tavilyApiKey: process.env.TAVILY_API_KEY ?? "",
  hallucinationLlmApiKey: process.env.HALLUCINATION_LLM_API_KEY ?? "",
  hallucinationLlmModel: process.env.HALLUCINATION_LLM_MODEL ?? "",
  enableMockAuth: process.env.NODE_ENV !== "production" || process.env.ENABLE_MOCK_AUTH === "true",
};
